substitutions:
  friendly_name: Telnet Server

esphome:
  name: telnet-example

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
  
external_components:
  - source: github://RoboMagus/esphome-telnet-server

wifi:
  ssid: !secret WiFi_ssid
  password: !secret WiFi_password

# Enable Home Assistant API
api:
  password: !secret hass_api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
    
logger:
  level: VERBOSE # this will also show lines received on Serial in Log output

telnet_server:
  port: 25 # defaut is 23
  client_count:
    name: "${friendly_name} client count"
  client_ips:
    name: "${friendly_name} client IPs"
